#!/usr/bin/env bash
set -euo pipefail

PACKAGE_ROOT="$1"
OUTPUT_DIR="$2"
REPOSITORY_ROOT="$(cd "${PACKAGE_ROOT}/../.." && pwd)"
MANIFEST="${PACKAGE_ROOT}/Docs/Certification/native-source-certification.json"
OUTPUT="${OUTPUT_DIR}/GeneratedSourceFingerprint.swift"

SOURCE_PATHS=()
while IFS= read -r relative_path; do
  SOURCE_PATHS+=("${relative_path}")
done < <(
  cd "${REPOSITORY_ROOT}"
  {
    /usr/bin/find macos/MyPTGuiNative/Sources/MyPTGuiEngine \
      -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' -o -name '*.m' -o -name '*.mm' \)
    /usr/bin/find macos/MyPTGuiNative/Sources/MyPTGuiCore macos/MyPTGuiNative/Sources/MyPTGuiApp \
      -type f -name '*.swift'
    /usr/bin/find native/metal_renderer \
      -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' -o -name '*.m' -o -name '*.metal' -o -name '*.mm' \)
    printf '%s\n' scripts/build_metal_renderer.sh
  } | LC_ALL=C /usr/bin/sort -u
)

if (( ${#SOURCE_PATHS[@]} == 0 )); then
  echo "Fingerprint source enumeration returned no files." >&2
  exit 1
fi

payload=""
separator=""
for relative_path in "${SOURCE_PATHS[@]}"; do
  absolute_path="${REPOSITORY_ROOT}/${relative_path}"
  if [[ ! -f "${absolute_path}" ]]; then
    echo "Missing fingerprint input: ${absolute_path}" >&2
    exit 1
  fi
  digest="$(/usr/bin/shasum -a 256 "${absolute_path}" | /usr/bin/awk '{print $1}')"
  payload="${payload}${separator}${relative_path}:${digest}"
  separator=$'\n'
done

current_fingerprint="$(printf '%s' "${payload}" | /usr/bin/shasum -a 256 | /usr/bin/awk '{print $1}')"
certified_fingerprint="$(/usr/bin/sed -nE 's/.*"certified_source_fingerprint"[[:space:]]*:[[:space:]]*"([0-9a-f]{64})".*/\1/p' "${MANIFEST}" | /usr/bin/head -n 1)"
certified_commit="$(/usr/bin/sed -nE 's/.*"certified_source_commit"[[:space:]]*:[[:space:]]*"([0-9a-f]{40})".*/\1/p' "${MANIFEST}" | /usr/bin/head -n 1)"
release_report_sha256="$(/usr/bin/sed -nE 's/.*"release_report_sha256"[[:space:]]*:[[:space:]]*"([0-9a-f]{64})".*/\1/p' "${MANIFEST}" | /usr/bin/head -n 1)"
metal_dylib_sha256="$(/usr/bin/sed -nE 's/.*"metal_dylib_sha256"[[:space:]]*:[[:space:]]*"([0-9a-f]{64})".*/\1/p' "${MANIFEST}" | /usr/bin/head -n 1)"
metal_api_version="$(/usr/bin/sed -nE 's/.*"metal_api_version"[[:space:]]*:[[:space:]]*([0-9]+).*/\1/p' "${MANIFEST}" | /usr/bin/head -n 1)"
if [[ ${#certified_fingerprint} -ne 64 ]]; then
  certified_fingerprint="uncertified"
fi
if [[ ${#certified_commit} -ne 40 ]]; then certified_commit="uncertified"; fi
if [[ ${#release_report_sha256} -ne 64 ]]; then release_report_sha256="uncertified"; fi
if [[ ${#metal_dylib_sha256} -ne 64 ]]; then metal_dylib_sha256="uncertified"; fi
if [[ ! ${metal_api_version} =~ ^[0-9]+$ ]]; then metal_api_version=0; fi

mkdir -p "${OUTPUT_DIR}"
temporary="${OUTPUT}.tmp"
{
  printf '%s\n' '// Generated by GenerateSourceFingerprintPlugin. Do not edit.'
  printf '%s\n' 'import Darwin'
  printf 'nonisolated(unsafe) private let currentFingerprint = UnsafePointer(strdup("%s")!)\n' "${current_fingerprint}"
  printf 'nonisolated(unsafe) private let certifiedFingerprint = UnsafePointer(strdup("%s")!)\n' "${certified_fingerprint}"
  printf 'nonisolated(unsafe) private let certifiedCommit = UnsafePointer(strdup("%s")!)\n' "${certified_commit}"
  printf 'nonisolated(unsafe) private let releaseReportSHA256 = UnsafePointer(strdup("%s")!)\n' "${release_report_sha256}"
  printf 'nonisolated(unsafe) private let metalDylibSHA256 = UnsafePointer(strdup("%s")!)\n' "${metal_dylib_sha256}"
  printf '%s\n' '@_cdecl("myptgui_build_engine_source_fingerprint")'
  printf '%s\n' 'public func myptguiBuildEngineSourceFingerprint() -> UnsafePointer<CChar> { currentFingerprint }'
  printf '%s\n' '@_cdecl("myptgui_build_certified_engine_source_fingerprint")'
  printf '%s\n' 'public func myptguiBuildCertifiedEngineSourceFingerprint() -> UnsafePointer<CChar> { certifiedFingerprint }'
  printf '%s\n' '@_cdecl("myptgui_build_certified_source_commit")'
  printf '%s\n' 'public func myptguiBuildCertifiedSourceCommit() -> UnsafePointer<CChar> { certifiedCommit }'
  printf '%s\n' '@_cdecl("myptgui_build_certified_release_report_sha256")'
  printf '%s\n' 'public func myptguiBuildCertifiedReleaseReportSHA256() -> UnsafePointer<CChar> { releaseReportSHA256 }'
  printf '%s\n' '@_cdecl("myptgui_build_certified_metal_dylib_sha256")'
  printf '%s\n' 'public func myptguiBuildCertifiedMetalDylibSHA256() -> UnsafePointer<CChar> { metalDylibSHA256 }'
  printf '%s\n' '@_cdecl("myptgui_build_certified_metal_api_version")'
  printf 'public func myptguiBuildCertifiedMetalAPIVersion() -> Int32 { %s }\n' "${metal_api_version}"
} > "${temporary}"

if [[ -f "${OUTPUT}" ]] && /usr/bin/cmp -s "${temporary}" "${OUTPUT}"; then
  rm "${temporary}"
else
  mv "${temporary}" "${OUTPUT}"
fi
